[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NetworkDynamics = "22e9dc34-2a0d-11e9-0de0-8588d035468b"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
